import type { QuizPackage, QuizQuestion } from '~/types/quiz'

export const quizQuestions: QuizQuestion[] = [
  {
    id: 1,
    text: 'Как вы обычно спите?',
    helpText: 'Это поможет подобрать рекомендации для улучшения качества сна и восстановления.',
    type: 'single',
    answers: [
      {
        id: 11,
        questionId: 1,
        text: 'Сплю хорошо, высыпаюсь',
        description: 'Просыпаюсь отдохнувшим и полным сил',
        icon: '☾',
        recommendationWeights: { balance: 2 },
      },
      {
        id: 12,
        questionId: 1,
        text: 'Бывают трудности',
        description: 'Иногда долго засыпаю или просыпаюсь ночью',
        icon: '◔',
        recommendationWeights: { balance: 2, recovery: 2 },
      },
      {
        id: 13,
        questionId: 1,
        text: 'Сплю плохо',
        description: 'Часто просыпаюсь, утро начинается с усталости',
        icon: '◑',
        recommendationWeights: { recovery: 4, checkup: 1 },
      },
      {
        id: 14,
        questionId: 1,
        text: 'Очень плохо',
        description: 'Проблемы со сном возникают почти каждый день',
        icon: '◒',
        recommendationWeights: { recovery: 5, checkup: 3 },
      },
    ],
  },
  {
    id: 2,
    text: 'Как часто вы чувствуете усталость в течение дня?',
    helpText: 'Ответ поможет оценить, какие обследования и процедуры могут быть полезны.',
    type: 'single',
    answers: [
      {
        id: 21,
        questionId: 2,
        text: 'Редко',
        description: 'Обычно энергии хватает на весь день',
        icon: '✦',
        recommendationWeights: { balance: 3 },
      },
      {
        id: 22,
        questionId: 2,
        text: 'Иногда',
        description: 'После насыщенных дней или недосыпа',
        icon: '◔',
        recommendationWeights: { balance: 2, recovery: 1 },
      },
      {
        id: 23,
        questionId: 2,
        text: 'Часто',
        description: 'Усталость мешает привычным делам',
        icon: '◑',
        recommendationWeights: { recovery: 3, checkup: 2 },
      },
      {
        id: 24,
        questionId: 2,
        text: 'Почти постоянно',
        description: 'Даже после отдыха сложно восстановить силы',
        icon: '◒',
        recommendationWeights: { recovery: 4, checkup: 4 },
      },
    ],
  },
  {
    id: 3,
    text: 'Насколько регулярно вы проходите базовые обследования?',
    helpText: 'Мы предложим удобный состав пакета без лишних процедур.',
    type: 'single',
    answers: [
      {
        id: 31,
        questionId: 3,
        text: 'Регулярно',
        description: 'Проверяю основные показатели каждый год',
        icon: '✓',
        recommendationWeights: { balance: 3 },
      },
      {
        id: 32,
        questionId: 3,
        text: 'Время от времени',
        description: 'Прохожу обследования раз в несколько лет',
        icon: '◔',
        recommendationWeights: { balance: 2, checkup: 2 },
      },
      {
        id: 33,
        questionId: 3,
        text: 'Только при необходимости',
        description: 'Обращаюсь, когда что-то беспокоит',
        icon: '!',
        recommendationWeights: { checkup: 4 },
      },
      {
        id: 34,
        questionId: 3,
        text: 'Давно не проходил обследования',
        description: 'Хочу получить понятную точку отсчета',
        icon: '+',
        recommendationWeights: { checkup: 5, recovery: 1 },
      },
    ],
  },
  {
    id: 4,
    text: 'Как вы оцениваете уровень стресса в последние недели?',
    helpText: 'Это не медицинская диагностика, а ориентир для персональной рекомендации.',
    type: 'single',
    answers: [
      {
        id: 41,
        questionId: 4,
        text: 'Низкий',
        description: 'Чувствую себя спокойно и устойчиво',
        icon: '○',
        recommendationWeights: { balance: 3 },
      },
      {
        id: 42,
        questionId: 4,
        text: 'Умеренный',
        description: 'Есть напряженные дни, но справляюсь',
        icon: '◔',
        recommendationWeights: { balance: 2, recovery: 1 },
      },
      {
        id: 43,
        questionId: 4,
        text: 'Высокий',
        description: 'Напряжение заметно влияет на самочувствие',
        icon: '◑',
        recommendationWeights: { recovery: 4 },
      },
      {
        id: 44,
        questionId: 4,
        text: 'Очень высокий',
        description: 'Мне сложно полноценно отдыхать и переключаться',
        icon: '◒',
        recommendationWeights: { recovery: 5, checkup: 1 },
      },
    ],
  },
]

export const quizPackages: QuizPackage[] = [
  {
    id: 1,
    code: 'balance',
    title: 'Базовый баланс',
    description: 'Плановый набор для контроля основных показателей и поддержания хорошего самочувствия.',
    price: 7900,
    services: [
      { id: 11, title: 'Общий анализ крови' },
      { id: 12, title: 'Базовая биохимия' },
      { id: 13, title: 'Консультация терапевта' },
    ],
    checkoutUrl: 'https://example.com/packages/balance',
  },
  {
    id: 2,
    code: 'recovery',
    title: 'Энергия и восстановление',
    description: 'Расширенная рекомендация для тех, кто хочет разобраться с усталостью и качеством отдыха.',
    price: 12900,
    services: [
      { id: 21, title: 'Расширенный анализ крови' },
      { id: 22, title: 'Проверка ключевых витаминов' },
      { id: 23, title: 'Консультация терапевта' },
      { id: 24, title: 'Персональные рекомендации по восстановлению' },
    ],
    checkoutUrl: 'https://example.com/packages/recovery',
    isPopular: true,
  },
  {
    id: 3,
    code: 'checkup',
    title: 'Расширенный чекап',
    description: 'Комплексная точка отсчета с более подробным набором анализов и итоговой консультацией.',
    price: 18900,
    services: [
      { id: 31, title: 'Расширенный анализ крови' },
      { id: 32, title: 'Биохимический профиль' },
      { id: 33, title: 'Проверка витаминов и микроэлементов' },
      { id: 34, title: 'Консультация терапевта по результатам' },
    ],
    checkoutUrl: 'https://example.com/packages/checkup',
  },
]
